# Generated by Django 5.0 on 2025-08-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='hotel_user',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='hotel_vendor',
        ),
    ]
